"""
MIRA configuration — safe local defaults.

All settings can be overridden via environment variables, but this prototype does
NOT require (and does not edit) any .env file. The defaults are deliberately the
safest possible: mock provider only, local LLM disabled, conservative row caps.
"""

from __future__ import annotations

import os


def _env_flag(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}


# ── Provider selection ──────────────────────────────────────────────────────────
# "mock"  -> mockMiraProvider     (default, rule-based, no external calls)
# "local" -> localLlmProviderStub (disabled stub; requires explicit IT approval)
PROVIDER_MODE = os.environ.get("MIRA_PROVIDER", "mock").strip().lower()

# Hard gate for the local-LLM stub. Even if PROVIDER_MODE=="local", the stub stays
# inert unless this is explicitly enabled by an approver.
LOCAL_LLM_ENABLED = _env_flag("MIRA_LOCAL_LLM_ENABLED", False)

# ── Privacy guard limits ────────────────────────────────────────────────────────
# Limited Filtered Rows Mode only — never the full dataset.
ROW_CAP_DEFAULT = int(os.environ.get("MIRA_ROW_CAP_DEFAULT", "15"))
ROW_CAP_MAX = int(os.environ.get("MIRA_ROW_CAP_MAX", "25"))

# Label stamped on every MIRA output.
DRAFT_LABEL = "Draft generated by MIRA for review"

# Disclaimer surfaced in responses / reports / docs.
MODEL_DISCLAIMER = (
    "Training a full Transformer model from scratch is not included in this "
    "prototype. MIRA is a controlled local assistant layer using dashboard KPI "
    "tools. A local LLM or approved AI service can be connected later if approved "
    "by IT."
)

# Default forward-looking window already used by the dashboard PM logic.
DEFAULT_STAGE = "all"
