/*
 * MIRA — Maintenance Intelligence & Reporting Assistant (frontend panel).
 *
 * A self-contained assistant panel mounted into #mira-root on the Maintenance
 * page. It talks ONLY to the local backend routes (/api/mira/*), which return
 * privacy-approved KPI summaries from the mockMiraProvider. It never reads raw
 * Excel/D365, never calls an external AI API, never exposes keys, and never logs
 * full work-order records to the console.
 *
 * Disable without touching the dashboard:  window.ENABLE_MIRA = false
 * (or window.MIRA_CONFIG = { enabled: false }).
 */
(function () {
    "use strict";

    const CFG = window.MIRA_CONFIG || { enabled: true, apiBase: "/api/mira" };
    const API = CFG.apiBase || "/api/mira";
    const MONTHS = ["January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "Dec"];
    const MONTHS_SHORT = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    // UI options only — not raw data. Mirrors Asset_Master main groups.
    const ASSET_GROUPS = ["Production Equipment", "Refrigeration", "Utilities", "Facility / Building"];

    const GUIDED = [
        { key: "summary", label: "Summarise this month", icon: "📅" },
        { key: "mttr", label: "Analyse MTTR", icon: "🛠️" },
        { key: "mtbf", label: "Analyse MTBF", icon: "⏱️" },
        { key: "open_wo", label: "Find open work orders", icon: "📋" },
        { key: "data_quality", label: "Check data reliability", icon: "🔎" },
        { key: "pm", label: "Summarise PM schedule", icon: "🗓️" },
        { key: "report", label: "Generate monthly report draft", icon: "📝" },
    ];

    let lastReportMarkdown = null;
    let lastReportName = "MIRA_monthly_report_draft.md";

    document.addEventListener("DOMContentLoaded", init);

    async function init() {
        const root = document.getElementById("mira-root");
        const tabBtn = document.querySelector("[data-mira-tab]");
        if (!root) return;

        // Feature flag: IT can disable MIRA without affecting the dashboard.
        if (CFG.enabled === false) {
            hideMira(tabBtn);
            return;
        }

        // Only surface MIRA if the local backend is actually available.
        let healthy = false;
        try {
            const res = await fetch(`${API}/health`, { cache: "no-store" });
            healthy = res.ok;
        } catch (_e) {
            healthy = false;
        }
        if (!healthy) {
            hideMira(tabBtn);
            console.warn("MIRA disabled: assistant backend not available.");
            return;
        }

        if (tabBtn) tabBtn.hidden = false;
        renderShell(root);
        bindEvents(root);
    }

    function hideMira(tabBtn) {
        if (tabBtn) tabBtn.hidden = true;
        document.getElementById("mira-view")?.classList.add("hidden");
    }

    // ── Shell markup ─────────────────────────────────────────────────────────
    function renderShell(root) {
        const now = new Date();
        const years = [now.getFullYear(), now.getFullYear() - 1, now.getFullYear() - 2];
        root.innerHTML = `
        <div class="mira-card mira-head-card">
            <div class="mira-head">
                <div class="mira-brand">
                    <span class="mira-logo">🤖</span>
                    <div>
                        <h2>MIRA — Maintenance Intelligence &amp; Reporting Assistant</h2>
                        <p class="mira-sub">Explains, searches and summarises using approved dashboard KPI outputs. The dashboard remains the source of truth.</p>
                    </div>
                </div>
                <span class="mira-draft-pill" title="MIRA output is a draft for human review">Draft analysis generated by MIRA for review</span>
            </div>
            <div class="mira-filters" role="group" aria-label="MIRA filters">
                <label class="mira-field"><span>Stage</span>
                    <select id="mira-f-stage">
                        <option value="all">All Stages</option>
                        <option value="stage1">Stage 1</option>
                        <option value="stage2">Stage 2</option>
                    </select>
                </label>
                <label class="mira-field"><span>Year</span>
                    <select id="mira-f-year">${years.map((y) => `<option value="${y}">${y}</option>`).join("")}</select>
                </label>
                <label class="mira-field"><span>Month</span>
                    <select id="mira-f-month">
                        <option value="">All months (YTD)</option>
                        ${MONTHS_SHORT.map((m, i) => `<option value="${i + 1}">${m}</option>`).join("")}
                    </select>
                </label>
                <label class="mira-field"><span>Asset Group</span>
                    <select id="mira-f-group">
                        <option value="">All groups</option>
                        ${ASSET_GROUPS.map((g) => `<option value="${g}">${g}</option>`).join("")}
                    </select>
                </label>
            </div>
        </div>

        <div class="mira-card">
            <div class="mira-section-label">Guided actions</div>
            <div class="mira-actions">
                ${GUIDED.map((a) => `<button type="button" class="mira-action" data-mira-action="${a.key}"><span aria-hidden="true">${a.icon}</span>${a.label}</button>`).join("")}
            </div>
            <div class="mira-ask">
                <input id="mira-input" type="text" class="mira-input"
                    placeholder="Ask a maintenance question, e.g. &quot;What is the MTTR for Stage 2 this month?&quot;"
                    autocomplete="off">
                <button type="button" id="mira-ask-btn" class="mira-ask-btn">Ask MIRA</button>
            </div>
        </div>

        <div id="mira-report" class="mira-card mira-report" hidden>
            <div class="mira-report-head">
                <div class="mira-section-label">Monthly Maintenance Report Draft</div>
                <button type="button" id="mira-download" class="mira-download">⬇ Download .md</button>
            </div>
            <div id="mira-report-body" class="mira-report-body"></div>
        </div>

        <div class="mira-card mira-responses-card">
            <div class="mira-section-label">Responses</div>
            <div id="mira-responses" class="mira-responses">
                <p class="mira-empty">Pick a guided action or ask a question to see a draft answer here.</p>
            </div>
        </div>`;
    }

    function bindEvents(root) {
        root.querySelectorAll("[data-mira-action]").forEach((btn) => {
            btn.addEventListener("click", () => runAction(btn.dataset.miraAction));
        });
        root.querySelector("#mira-ask-btn")?.addEventListener("click", runAsk);
        root.querySelector("#mira-input")?.addEventListener("keydown", (e) => {
            if (e.key === "Enter") runAsk();
        });
        root.querySelector("#mira-download")?.addEventListener("click", downloadReport);
    }

    // ── Filters ──────────────────────────────────────────────────────────────
    function val(id, fallback) {
        const node = document.getElementById(id);
        return node && node.value !== "" ? node.value : (fallback !== undefined ? fallback : "");
    }
    function getFilters() {
        return {
            stage: val("mira-f-stage", "all"),
            year: val("mira-f-year", String(new Date().getFullYear())),
            month: val("mira-f-month", ""),          // "" → YTD on the backend
            mainAssetGroup: val("mira-f-group", ""),
        };
    }

    // Light client-side extraction so free-text questions can override the selectors.
    function extractFilters(question, base) {
        const f = Object.assign({}, base);
        const t = (question || "").toLowerCase();
        if (/stage\s*2|\bs2\b/.test(t)) f.stage = "stage2";
        else if (/stage\s*1|\bs1\b/.test(t)) f.stage = "stage1";
        else if (/all stages|both stages/.test(t)) f.stage = "all";

        const now = new Date();
        if (/this month/.test(t)) { f.year = String(now.getFullYear()); f.month = String(now.getMonth() + 1); }
        else if (/last month/.test(t)) {
            const d = new Date(now.getFullYear(), now.getMonth() - 1, 1);
            f.year = String(d.getFullYear()); f.month = String(d.getMonth() + 1);
        } else if (/ytd|year to date|this year/.test(t)) { f.month = ""; }

        MONTHS.forEach((m, i) => { if (t.includes(m.toLowerCase()) || t.includes(MONTHS_SHORT[i].toLowerCase())) f.month = String(i + 1); });
        const ym = t.match(/\b(20\d{2})\b/);
        if (ym) f.year = ym[1];
        ASSET_GROUPS.forEach((g) => { if (t.includes(g.toLowerCase().split(" ")[0])) f.mainAssetGroup = g; });
        return f;
    }

    // ── Backend calls ────────────────────────────────────────────────────────
    async function callMira(path, body) {
        const res = await fetch(`${API}${path}`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            cache: "no-store",
            body: JSON.stringify(body || {}),
        });
        if (!res.ok) throw new Error(`MIRA ${path} → HTTP ${res.status}`);
        return res.json();
        // NOTE: response intentionally NOT logged to console (no raw rows in console).
    }

    const ACTION_MAP = {
        summary: { path: "/summary" },
        mttr: { path: "/mttr" },
        mtbf: { path: "/mtbf" },
        open_wo: { path: "/work-orders", extra: { status: "open" }, limit: 15 },
        data_quality: { path: "/data-quality" },
        pm: { path: "/pm-schedule" },
        report: { path: "/report-draft" },
    };

    async function runAction(key) {
        const cfg = ACTION_MAP[key];
        if (!cfg) return;
        const filters = getFilters();
        // "Summarise this month" honours its label by targeting the current month.
        if (key === "summary") {
            const now = new Date();
            filters.month = String(now.getMonth() + 1);
            filters.year = String(now.getFullYear());
            const sel = document.getElementById("mira-f-month");
            if (sel) sel.value = filters.month;
        }
        Object.assign(filters, cfg.extra || {});
        const body = { filters };
        if (cfg.limit) body.limit = cfg.limit;

        if (key === "report") return runReport(filters);

        setBusy(true);
        try {
            const resp = await callMira(cfg.path, body);
            renderAnswer(resp);
        } catch (err) {
            renderError(err);
        } finally {
            setBusy(false);
        }
    }

    async function runAsk() {
        const input = document.getElementById("mira-input");
        const question = (input?.value || "").trim();
        if (!question) return;
        const filters = extractFilters(question, getFilters());
        setBusy(true);
        try {
            const resp = await callMira("/query", { question, filters });
            renderAnswer(resp, question);
            // Drafting a report by typing it too.
            if (resp.intent === "monthly_summary" && /report/i.test(question)) {
                await runReport(filters);
            }
        } catch (err) {
            renderError(err);
        } finally {
            setBusy(false);
            if (input) input.value = "";
        }
    }

    async function runReport(filters) {
        setBusy(true);
        try {
            const resp = await callMira("/report-draft", { filters });
            renderReport(resp);
            renderAnswer({
                ok: true, intent: "report_draft", mode: "report_draft",
                answer: resp.narrative, data: {}, provider: resp.provider,
            });
        } catch (err) {
            renderError(err);
        } finally {
            setBusy(false);
        }
    }

    // ── Rendering ────────────────────────────────────────────────────────────
    const INTENT_LABELS = {
        monthly_summary: "Monthly Summary", mttr: "MTTR", mtbf: "MTBF",
        open_work_orders: "Open Work Orders", preventive_corrective: "Preventive vs Corrective",
        data_quality: "Data Reliability", pm_schedule: "PM Schedule",
        stage_compare: "Stage 1 vs Stage 2", work_order_search: "Work Order Search",
        report_draft: "Report Draft",
    };

    function sourceLabel(mode) {
        if (mode === "limited_filtered_rows") return "Based on limited, filtered work orders (field-reduced)";
        if (mode === "report_draft") return "Based on dashboard KPI summary";
        return "Based on dashboard KPI summary";
    }

    function looksIncomplete(resp) {
        const a = (resp.answer || "").toLowerCase();
        if (a.includes("not available")) return true;
        const d = resp.data || {};
        if (d.work_orders && Number(d.work_orders.total) === 0) return true;
        if (resp.mode === "limited_filtered_rows" && Number(d.total_matched) === 0) return true;
        if (typeof d.total_work_orders === "number" && d.total_work_orders === 0) return true;
        return false;
    }

    function renderAnswer(resp, question) {
        const host = document.getElementById("mira-responses");
        if (!host) return;
        host.querySelector(".mira-empty")?.remove();

        const card = document.createElement("article");
        card.className = "mira-answer";

        const head = document.createElement("div");
        head.className = "mira-answer-head";
        const tag = document.createElement("span");
        tag.className = "mira-intent";
        tag.textContent = INTENT_LABELS[resp.intent] || "Answer";
        const src = document.createElement("span");
        src.className = "mira-source";
        src.textContent = sourceLabel(resp.mode);
        head.appendChild(tag);
        head.appendChild(src);
        card.appendChild(head);

        if (question) {
            const q = document.createElement("p");
            q.className = "mira-q";
            q.textContent = `You asked: ${question}`;
            card.appendChild(q);
        }

        const body = document.createElement("div");
        body.className = "mira-answer-body";
        body.textContent = resp.answer || "(no answer)";   // textContent — never innerHTML from data
        card.appendChild(body);

        if (resp.mode === "limited_filtered_rows" && resp.data && Array.isArray(resp.data.rows)) {
            card.appendChild(buildRowTable(resp.data));
        }

        if (looksIncomplete(resp)) {
            const warn = document.createElement("div");
            warn.className = "mira-warn";
            warn.textContent = "⚠ Data looks incomplete for this window (e.g. no imported work orders). Try a wider period such as All months (YTD), and verify against the dashboard.";
            card.appendChild(warn);
        }

        const foot = document.createElement("div");
        foot.className = "mira-answer-foot";
        foot.textContent = `${resp.provider ? "Provider: " + resp.provider + " · " : ""}Draft generated by MIRA for review`;
        card.appendChild(foot);

        host.prepend(card);
    }

    function buildRowTable(data) {
        const wrap = document.createElement("div");
        wrap.className = "mira-table-wrap";
        const meta = document.createElement("div");
        meta.className = "mira-table-meta";
        meta.textContent = `Showing ${data.returned_rows} of ${data.total_matched} matched (max ${data.row_cap}, sensitive fields removed).`;
        wrap.appendChild(meta);

        const rows = data.rows || [];
        if (!rows.length) return wrap;
        const cols = ["work_order_id", "asset_id", "asset_display_name", "machine_group", "status_category", "ttr_hours", "data_quality_flag"];
        const labels = ["WO ID", "Asset ID", "Asset", "Group", "Status", "TTR (h)", "Quality"];
        const table = document.createElement("table");
        table.className = "mira-table";
        const thead = document.createElement("thead");
        const htr = document.createElement("tr");
        labels.forEach((l) => { const th = document.createElement("th"); th.textContent = l; htr.appendChild(th); });
        thead.appendChild(htr);
        table.appendChild(thead);
        const tbody = document.createElement("tbody");
        rows.forEach((r) => {
            const tr = document.createElement("tr");
            cols.forEach((c) => {
                const td = document.createElement("td");
                const v = r[c];
                td.textContent = (v === null || v === undefined || v === "") ? "—" : String(v);
                tr.appendChild(td);
            });
            tbody.appendChild(tr);
        });
        table.appendChild(tbody);
        wrap.appendChild(table);
        return wrap;
    }

    function renderReport(resp) {
        const panel = document.getElementById("mira-report");
        const body = document.getElementById("mira-report-body");
        if (!panel || !body) return;
        body.innerHTML = "";

        const title = document.createElement("h3");
        title.className = "mira-report-title";
        title.textContent = resp.title || "Maintenance Report Draft";
        body.appendChild(title);

        const pill = document.createElement("div");
        pill.className = "mira-draft-pill inline";
        pill.textContent = resp.draft_label || "Draft generated by MIRA for review";
        body.appendChild(pill);

        const narrative = document.createElement("p");
        narrative.className = "mira-report-narrative";
        narrative.textContent = resp.narrative || "";
        body.appendChild(narrative);

        (resp.sections || []).forEach((sec) => {
            const h = document.createElement("h4");
            h.textContent = sec.title;
            body.appendChild(h);
            const dl = document.createElement("dl");
            dl.className = "mira-report-metrics";
            Object.entries(sec.metrics || {}).forEach(([k, v]) => {
                const dt = document.createElement("dt"); dt.textContent = k;
                const dd = document.createElement("dd"); dd.textContent = (v === null || v === undefined) ? "not available" : String(v);
                dl.appendChild(dt); dl.appendChild(dd);
            });
            body.appendChild(dl);
        });

        const disc = document.createElement("p");
        disc.className = "mira-report-disclaimer";
        disc.textContent = resp.disclaimer || "";
        body.appendChild(disc);

        lastReportMarkdown = resp.markdown || null;
        const win = (resp.window || "report").replace(/\s+/g, "_");
        lastReportName = `MIRA_report_${win}.md`;
        panel.hidden = false;
        panel.scrollIntoView({ behavior: "smooth", block: "nearest" });
    }

    function downloadReport() {
        if (!lastReportMarkdown) return;
        const blob = new Blob([lastReportMarkdown], { type: "text/markdown;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = lastReportName;
        document.body.appendChild(a);
        a.click();
        a.remove();
        setTimeout(() => URL.revokeObjectURL(url), 1000);
    }

    function renderError(err) {
        const host = document.getElementById("mira-responses");
        if (!host) return;
        host.querySelector(".mira-empty")?.remove();
        const card = document.createElement("article");
        card.className = "mira-answer mira-answer-error";
        card.textContent = `MIRA could not complete that request. ${err && err.message ? err.message : ""}`.trim();
        host.prepend(card);
        console.warn("MIRA request failed:", err && err.message ? err.message : err);  // message only, no data
    }

    function setBusy(busy) {
        const btns = document.querySelectorAll("#mira-root .mira-action, #mira-ask-btn");
        btns.forEach((b) => { b.disabled = busy; });
        const ask = document.getElementById("mira-ask-btn");
        if (ask) ask.textContent = busy ? "Thinking…" : "Ask MIRA";
    }
})();
